branch-defaults:
  act_test_v1:
    environment: my-env
    group_suffix: null
global:
  application_name: my-orchestration-app
  branch: null
  default_ec2_keyname: null
  default_platform: Docker
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
